import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";


const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	introduction: [{type: "autogenerated", dirName: "introduction"}],
	model: [{type: "autogenerated", dirName: "sheet"}],
	commands: [{type: "autogenerated", dirName: "usage"}],
	TOS: [{type: "autogenerated", dirName: "dev"}],
};

export default sidebars;
