name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build]
permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Fetch submodule
        continue-on-error: true
        run: |
          git submodule update --init --recursive --remote --force
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update submodule"
          git push
      - name: Install dependencies
        run: pnpm install
      - name: Build website
        run: pnpm run build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
