name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build]
permissions:
  contents: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"
      - name: Fetch submodule
        continue-on-error: true
        run: |
          git submodule update --init --recursive --remote --force
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update submodule"
          git push
  build:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build website
        run: bun run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
